# Generated by Django 5.2.7 on 2025-10-06 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'indexes': [models.Index(fields=['categoryName'], name='categories_categor_b128a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=255)),
                ('contactName', models.CharField(blank=True, max_length=255, null=True)),
                ('contactTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customers',
                'indexes': [models.Index(fields=['companyName'], name='customers_company_b8fb97_idx'), models.Index(fields=['city'], name='customers_city_98cb62_idx')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('reportsTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='data_loader.employee')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.IntegerField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(blank=True, null=True)),
                ('requiredDate', models.DateTimeField(blank=True, null=True)),
                ('shippedDate', models.DateTimeField(blank=True, null=True)),
                ('freight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customerID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.customer')),
                ('employee', models.ForeignKey(blank=True, db_column='employeeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.employee')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('quantityPerUnit', models.CharField(blank=True, max_length=255, null=True)),
                ('unitPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discontinued', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, db_column='categoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='data_loader.order')),
                ('product', models.ForeignKey(blank=True, db_column='productID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.product')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('shipperID', models.IntegerField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shippers',
                'indexes': [models.Index(fields=['companyName'], name='shippers_company_5b5507_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, db_column='shipperID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.shipper'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employeeName'], name='employees_employe_66e2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['productName'], name='products_product_60efa9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_e6feff_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['order'], name='order_detai_orderID_fd74e8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['product'], name='order_detai_product_1fdb35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'product')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['orderDate'], name='orders_orderDa_77eb05_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='orders_custome_052b1a_idx'),
        ),
    ]
