# Generated by Django 5.2.7 on 2025-10-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nl_query', models.TextField()),
                ('generated_sql', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='created', max_length=32)),
                ('error', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
